#!/usr/bin/perl

#givwn a list count how many time every element of the list occours
if (@ARGV < 1 ) {
	print "1.arg = list\n";
        }
`sort @ARGV[0] > freq_count_temp_sorted`;

open (IN, "freq_count_temp_sorted") 
or die "can not open list file\n";
$a=1;
$b=0;
while (<IN>) {
      chomp;
      $entry_old=$entry;
      ($entry) = $_ =~ /(.+)/;
      if ($b == 1)  {
          if ($entry eq $entry_old) {
             $a++;
             } else {
                  push (@out,"$entry_old\t$a\n");
                  $a=1;
                 }
     }else{$b=1}
}
 push (@out,"$entry\t$a\n");
`rm freq_count_temp_sorted`;
print @out;
