#!/usr/bin/perl


use lib $ENV{"HOME"}.'/bion_tools';

use menafmod;

$infile = $ARGV[0]; # file
$del = $ARGV[1];   #delimitator

                  (@transponed) = &transpose_file($infile);

print join ("\n",@transponed);

